# ---------------------------
# KEYBOARD LAYOUTS
# ---------------------------
# Awailable layouts
xkb_rules_layout=us,ru

# Layouts variations
# NOTE: QWERTY is default
xkb_rules_variant=,

# Make layout switch by pressing both alts
# Make CapsLock button act as a backspace
# NOTE: It's possible to switch layouts using switch_keyboard_layout function in bindings
xkb_rules_options=grp:alts_toggle,caps:backspace

# ---------------------------
# KEYBOARD
# ---------------------------
# Characters per second while a key is held
# 0: Disables repeat
# Mango range: 1–1000
repeat_rate=25

# Milliseconds before key repeat starts
# Mango range: 1–20000
repeat_delay=600

# Enable NumLock when the compositor starts
# 1: True
# 0: False
numlockon=0

# ---------------------------
# MOUSE
# ---------------------------
# Invert scrolling direction
# 1: True
# 0: False
mouse_natural_scrolling=0

# Mouse acceleration profile
# 0: None
# 1: Flat. Constant pointer speed
# 2: Adaptive. Speed varies with velocity
mouse_accel_profile=1

# Mouse speed adjustment
# Negative slows down, positive speeds up
# Mango range: -1.0 to 1.0
mouse_accel_speed=0.0

# Swap left and right buttons
left_handed=0

# Multiplier for mouse scroll speed
# Mango range: 0.1–10.0
axis_scroll_factor=1.0

# ---------------------------
# TRACKPAD
# ---------------------------
# Disable trackpad
# 1: True
# 0: False
disable_trackpad=0

# Invert scrolling direction
trackpad_natural_scrolling=1

# Multiplier for trackpad scroll speed
# Mango range: 0.1–10.0
trackpad_scroll_factor=1.0

# Swap left/right buttons
# 1: True
# 0: False
left_handed=0

# Button Map
# 0: Left/Right/Middle (LRM)
# 1: Left/Middle/Right (LMR)
button_map=1

# Tap to trigger a left click
tap_to_click=1

# Double-tap and hold to drag items
tap_and_drag=1

# Lock dragging after tapping
# 1: True
# 0: False
drag_lock=1

# Trackpad acceleration profile
# 0: None
# 1: Flat. Constant pointer speed
# 2: Adaptive. Speed varies with velocity
trackpad_accel_profile=1

# Trackpad speed adjustment
# Negative slows down, positive speeds up
# Mango range: -1.0 to 1.0
trackpad_accel_speed=0.5

# The mouse button that use for scrolling
# 272 to 279
scroll_button=274

# Scroll method
# 0: No Scrolling
# 1: Two-finger
# 2: Edge. Send scroll events when a finger moves along the bottom or right edge
# 4: Button. Send scroll events when a button is held and the device moves along a scroll axis
scroll_method=1

# Click method
# 0: No software emulation
# 1: Button areas. Use software-defined areas on the touchpad to generate button events
# 2: Clickfinger. The number of fingers determines which button is pressed
click_method=1

# Send events mode
# 0: Enabled. Send events from trackpad normally.
# 1: Disabled. Do not send events from this device
# 2: Disabled on external mouse. Disable trackpad if an exteral mouse is plugged in
send_events_mode=0

# Disable trackpad while typing on a keyboard
# 1: True
# 0: False
disable_while_typing=1

# Emulate middle button
# By pressing left and right buttons together
# 1: True
# 0: False
middle_button_emulation=0

# Minimum pointer movement in pixels to trigger a swipe gesture
# Higher values reduce accidental triggers
# Mango range: 1–1000
swipe_min_threshold=1
