focused_opacity = 1.0
unfocused_opacity = 0.75


windowrule=unfocused_opacity:1.0,appid:zen

# Example scroller configuration
scroller_structs=20
scroller_default_proportion=0.5
scroller_focus_center=0
scroller_prefer_center=0
scroller_prefer_overspread=1
edge_scroller_pointer_focus=1
edge_scroller_focus_allow_speed=0.0
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,1.0

tagrule=id:1,no-hide:1,layout_name:scroller
# tagrule=id:2, no-hide:, layout_name:tile
