# -----------------------
# RENDERING
# -----------------------
# Global Tearing Control (Game Mode)
# 0: Disable
# 1: Enable
# 2: Fullscreen Only
allow_tearing = 2

# HDR Depth for the current display
# NOTE: Enable HDR in montorrule first
# IMPORTANT: env=WLR_RENDERER,vukan must be set before mango starts
# 0: Default
# 1: HDR8
# 2: HDR10
hdr_depth = 0

