# ---------------------------
# KEYBOARD LAYOUTS
# ---------------------------
xkb_rules_layout=us,ru
xkb_rules_variant=,
xkb_rules_options=grp:alts_toggle,caps:backspace

# ---------------------------
# INPUT
# ---------------------------
trackpad_natural_scrolling=1

# ---------------------------
# AUTOSTART SCRIPTS
# ---------------------------
# Convenience script. Automatically switches to Tag 1 if current tag is empty
# Pretty convenient if you close all the windows in current tag
exec-once=nu ~/.config/mango/shell-scripts/autotag.nu

