# -----------------------
# APPS
# -----------------------
# Open Browser
bind=SUPER,b,spawn_shell,~/.config/mango/shell-scripts/open-browser.nu 

# Open Browser with new tab
bind=SUPER+SHIFT,b,spawn_shell,~/.config/mango/shell-scripts/open-browser.nu --newtab

# Open Telegram
bind=SUPER+SHIFT,m,spawn_shell,~/.config/mango/shell-scripts/open-telegram.nu
# -----------------------
# UTILS
# -----------------------
# Open editor in a directory of focused terminal or in home directory
bind=SUPER,e,spawn_shell, ~/.config/mango/shell-scripts/open-editor.nu

# Open GitRepos Explorer window
bind=SUPER+SHIFT,e,spawn_shell,~/.config/mango/shell-scripts/turn-on-tv.nu --class=Explorer --title=GitRepos -- explorer-gitrepos

# Open dotfiles configs
bind=SUPER+SHIFT,c,spawn_shell,~/.config/mango/shell-scripts/turn-on-tv.nu --class=Explorer --title="Configs" -- explorer-configs
# -----------------------
# WINDOWS
# -----------------------
# Toggle global
bind=SUPER,g,toggleglobal

# Toggle maximise screen
bind=SUPER,f,togglemaximizescreen

# Toggle fullscreen
bind=SUPER+SHIFT,f,togglefullscreen

# Toggle fake fullscreen
bind=SUPER+ALT,f,togglefakefullscreen

# -----------------------
# OVERVIEW
# -----------------------
# Enter jump overview
bind=SUPER,o,togglejump
# Enter jump overview
bind=ALT,tab,togglejump

# -----------------------
# LAYOUTS
# -----------------------
# Switch proportion preset for scroller
bind=SUPER+SHIFT,p,switch_proportion_preset

# -----------------------
# SCRATCHPADS
# -----------------------
# Send currenrt window to the scratchpad
bind=SUPER,i,minimized

# Toggle (show/hide) the scratchpad
bind=ALT,z,toggle_scratchpad

# Retrieve window from scratchpad
bind=SUPER+SHIFT,i,restore_minimized

# Open Terminal Scratchpad
bind=SUPER,t,toggle_named_scratchpad,scratch.term,none,~/.config/mango/shell-scripts/open-scratch-terminal.nu

# Open Notes Scratchpad
bind=SUPER,n,toggle_named_scratchpad,none,Notes,~/.config/mango/shell-scripts/open-notes.nu
