# ---------------------------
# TAG RULES
# ---------------------------
tagrule=id:*,layout_name:scroller,scroller_default_proportion_single:1.0

# Main is scroller for comfort
tagrule=id:1,no_hide:1,layout_name:scroller,scroller_default_proportion_single:1.0

# Use for telegram, discord, and other communication apps
tagrule=id:2,no_hide:1,layout_name:fair

