# ---------------------------
# KEYBOARD LAYOUTS
# ---------------------------
xkb_rules_layout=us,ru
xkb_rules_variant=,
xkb_rules_options=grp:alts_toggle,caps:backspace

# ---------------------------
# INPUT
# ---------------------------
trackpad_natural_scrolling=1

# ---------------------------
# OPACITY
# ---------------------------
# Make separate window rules keep windows opaque
focused_opacity = 1.0
unfocused_opacity = 0.75

# ---------------------------
# BLUR
# ---------------------------

blur=1
blur_layer=0
blur_opitmized=1
blur_params_radius=5
blur_params_num_passes=2

# ---------------------------
# SCRATCHPAD
# ---------------------------
scratchpad_width_ratio=0.6
scratchpad_height_ratio=0.8
scratchpadcolor=0x516c93ff

# ---------------------------
# OVERVIEW
# ---------------------------
ov_tab_mode=0

# ---------------------------
# ANIMATIONS
# ---------------------------
animations=1
layer_animations=1
animation_type_open=zoom
animation_type_close=zoom
animation_fade_in=1
animation_fade_out=1

animation_duration_open=400
animation_duration_close=300

zoom_initial_ratio=0.3
zoom_end_ratio=0.8

tag_animation_direction=0

# ---------------------------
# AUTOSTART SCRIPTS
# ---------------------------
# Convenience script. Automatically switches to Tag 1 if current tag is empty
# Pretty convenient if you close all the windows in current tag
exec-once=nu ~/.config/mango/shell-scripts/autotag.nu

