# -----------------------
# UTILS
# -----------------------
bind=SUPER,e,spawn,nu ~/.config/mango/shell-scripts/open-editor.nu

# -----------------------
# WINDOWS
# -----------------------
# Toggle global
bind=SUPER,g,toggleglobal

# Toggle maximise screen
bind=SUPER,f,togglemaximizescreen

# Toggle fullscreen
bind=SUPER+SHIFT,f,togglefullscreen

# Toggle fake fullscreen
bind=SUPER+ALT,f,togglefakefullscreen

# -----------------------
# OVERVIEW
# -----------------------
# Enter jump overview
bind=SUPER,o,togglejump
# Enter jump overview
bind=ALT,tab,togglejump

# -----------------------
# LAYOUTS
# -----------------------
# Switch proportion preset for scroller
bind=SUPER+SHIFT,p,switch_proportion_preset

# -----------------------
# SCRATCHPADS
# -----------------------
# Send currenrt window to the scratchpad
bind=SUPER,i,minimized

# Toggle (show/hide) the scratchpad
bind=ALT,z,toggle_scratchpad

# Retrieve window from scratchpad
bind=SUPER+SHIFT,i,restore_minimized

# Open Terminal Scratchpad
bind=SUPER,t,toggle_named_scratchpad,scratch-term,none,kitty --class scratch-term --config ~/.config/kitty/kitty-no-tabs.conf

# Open Notes Scratchpad
bind=SUPER,n,toggle_named_scratchpad,notes-scratch,none,kitty --class notes-scratch --config ~/.config/kitty/kitty-no-tabs.conf -e ~/.config/mango/shell-scripts/open-notes.nu
