# Terminals
windowrule=appid:kitty,isterm:1

# GitRepos Explorer
windowrule=appid:Explorer,title:GitRepos,isfloating:1,width:0.5,height:0.5,isoverlay:1

# Configs Explorer
windowrule=appid:Explorer,title:Configs,isfloating:1,width:0.5,height:0.5,isoverlay:1

# Zen Browser
windowrule=appid:zen,unfocused_opacity:1.0,tags:1

# Zen PnP
windowrule=appid:zen,title:Picture-in-Picture,isfloating:1,width:0.3,height:0.3,no_force_center:1,offsetx:100,offsety:100

# MPV
windowrule=appid:mpv,unfocused_opacity:1.0,tags:3,isfullscreen:1

# Terminal Scratchpad
windowrule=appid:scratch.term,isnamedscratchpad:1,width:0.5,height:0.75

# Notes Scratchpad
windowrule=title:Notes,isnamedscratchpad:1,width:0.5,height:0.75

# Swayimg
windowrule=appid:swayimg,unfocused_opacity:1.0

# Telegram
windowrule=appid:org.telegram.desktop,tags:2,ignore_minimize:1

# System Monitor
windowrule=title:System Monitor,isfloating:1,width:0.5,height:0.75,centerwin

