# -----------------------
# OVERVIEW
# -----------------------
# Enable hot areas
# 0: True
# 1: False
enable_hotarea=0

# Hot area size in pixels
hotarea_size=10

# Hot area corner
# 0: Top-left
# 1: Top-right
# 2: Bottom-left
# 3: Bottom-right
hotarea_corner=2

# Overview tab mode
# Will behave like a classic Alt+Tab
# NOTE: Doesn't work in jump overview
ov_tab_mode=1

# Inner gap in overview mode
overviewgappi=5

# Outer gap in overview mode
overviewgappo=30

# Character sequence used for jump hints in jump overview
# NOTE: Optimized for Gralmak layout
jump_labels=HAEISTRNYGFWPCODMULXBZ
