# Zen Browser
windowrule=unfocused_opacity:1.0, tags:1, appid:zen

# MPV
windowrule=unfocused_opacity:1.0, tags:3, isfullscreen:1, appid:mpv

# Terminal Scratchpad
windowrule=isnamedscratchpad:1, appid:scratch-term
