# -----------------------
# SCRATCHPADS
# -----------------------
# Send currenrt window to the scratchpad
bind=SUPER,i,minimized

# Toggle (show/hide) the scratchpad
bind=ALT,z,toggle_scratchpad

# Retrieve window from scratchpad
bind=SUPER+SHIFT,i,restore_minimized

# Open Terminal Scratchpad
bind=SUPER,t,toggle_named_scratchpad,scratch-term,none,kitty --class scratch-term --config ~/.config/kitty/kitty-no-tabs.conf
