# ---------------------------
# GENERAL
# ---------------------------
# Enable/Disable animations
animations=1

# Enable/Disable layer animations (bars/docks)
layer_animations=1

# Tag animation direction
# 1 - horizontal
# 0 - vertical
tag_animation_direction=0

# ---------------------------
# TYPES
# ---------------------------
# Available types: slide, zoom, fade, none

# Animation type when window opens
animation_type_open=zoom

# Animation type when window closes
animation_type_close=zoom

# Animation type when layer opens
layer_animation_type_open=slide

# Animation type when layer closes
layer_animation_type_close=slide

# ---------------------------
# FADE
# ---------------------------
# Enable/Disable fade-in effect
animation_fade_in=1

# Enable/Disable fade-out effect
animation_fade_out=1

# Starting opacity for fade-in
fadein_begin_opacity=0.5

# Starting opacity for fade-out
fadeout_begin_opacity=0.5

# ---------------------------
# ZOOM
# ---------------------------
# Initial zoom ratio
zoom_initial_ratio=0.3

# End zoom ratio
zoom_end_ratio=0.8

# ---------------------------
# DURATIONS
# ---------------------------
# Open animation duration (ms)
animation_duration_open=400

# Close animation duration (ms)
animation_duration_close=300

# Focus change (opacity transition) animation duration (ms)
animation_duration_focus=300

# Move animation duration (ms)
animation_duration_move=500

# Tag animation duration (ms)
animation_duration_tag=500

# ---------------------------
# BEZIER CURVES
# ---------------------------
# Bezier curves determine the "feel" of an animation (e.g., linear vs. bouncy).
# The format is x1,y1,x2,y2.
# You can visualize and generate curve values using online tools
# Like cssportal.com or easings.net.

# Open animation bezier curve
animation_curve_open=0.46,1.0,0.29,0.99

# Close animation bezier curve
animation_curve_close=0.46,1.0,0.29,0.99

# Focus change (opacity transition) animation bezier curve
animation_curve_focus=0.46,1.0,0.29,0.99

# Move animation bezier curve
animation_curve_move=0.46,1.0,0.29,0.99

# Tag animation bezier curve
animation_curve_tag=0.46,1.0,0.29,0.99

# Open opacity animation bezier curve
animation_curve_opafadein=0.46,1.0,0.29,0.99

Close opacity animation bezier curve
animation_curve_opafadeout=0.5,0.5,0.5,0.5
