# ---------------------------
# CURSOR THEME
# ---------------------------
# Cursor Size
cursor_size=24

# Cursor Theme
cursor_theme=Adwaita

# ---------------------------
# BORDERS
# ---------------------------
# Thickness of window borders in pixels
borderpx=4

# Window corner radius in pixels
border_radius=8

# Disable border radius if only one window is visible
no_radius_when_single=0

# ---------------------------
# GAPS
# ---------------------------
# Horizontal inner gap (between windows)
gappih=5

# Vertical inner gap (between windows)
gappiv=5

# Horizontal outer gap (between windows and screen edges)
gappoh=10

# Vertical outer gap (between windows and screen edges)
gappov=10

# ---------------------------
# COLORS
# ---------------------------
# IMPORTANT: Colors are defined in 0xRRGGBBAA hex format

# Background color of the root window
rootcolor=0x323232ff

# Inactive window border
bordercolor=0x444444ff

# Drop shadow when dragging windows
dropcolor=0x8FBA7C55

# Split window border color in manual dwindle layout
splitcolor=0xEB441EFF

# Active window border
focuscolor=0xc66b25ff

# Urgent window border (alerts)
urgentcolor=0xad401fff

# Maximized window color
maximizescreencolor=0x89aa61ff

# Scratchpad window color
scratchpadcolor=0x516c93ff

# Global (pinned) window color
globalcolor=0xb153a7ff

# Overlay window color
overlaycolor=0x14a57cff

# ---------------------------
# JUMP OVERVIEW MODE
# ---------------------------
# Text color
jump_label_decorate_fg_color=0x4939dff

# Background color
jump_label_decorate_bg_color=0x201b14ff

# Text color for focus
jump_label_decorate_focus_fg_color=0x201b14ff

# Background for focus
jump_label_decorate_focus_bg_color=0xc4939dff

# Border color
jump_label_decorate_border_color=0x8BAA9Bff

# Border width
jump_label_decorate_border_width=4

# Corner radius
jump_label_decorate_corner_radius=5

# Horizontal padding
jump_label_decorate_padding_x=10

# Vertical padding
jump_label_decorate_padding_y=10

# Font
jump_label_decorate_font_desc='JetBrains Mono NF' Bold 18


# ---------------------------
# WINDOW GROUP TAB BAR
# ---------------------------
# Height of the tab bar
group_bar_height=36

# Text color
group_bar_decorate_fg_color=0xc4939df

# Background color
group_bar_decorate_bg_color=0x201b14ff

# Text color for focus
group_bar_decorate_focus_fg_color=0x201b14ff

# Background color for focus
group_bar_decorate_focus_bg_color=0xc4939dff

# Border color
group_bar_decorate_border_color=0x8BAA9Bff

# Border width
group_bar_decorate_border_width=3

# Corner radius
group_bar_decorate_corner_radius=5

# Horizontal padding
group_bar_decorate_padding_x=0

# Vertical padding
group_bar_decorate_padding_y=0

# Font
group_bar_decorate_font_desc='JetBrains Mono NF' Regular 14

