

# ---------------------------
# AUTOSTART SCRIPTS
# ---------------------------
# Convenience script. Automatically switches to Tag 1 if current tag is empty
# Pretty convenient if you close all the windows in current tag
exec-once=nu ~/.config/mango/shell-scripts/autotag.nu

