# Set default volume to 60%
volume = 60

# Default settings for YouTube
hwdec=auto-safe
vo=gpu
ytdl-format=bestvideo[height<=?1080]+bestaudio/best[height<=?1080]

[linux-amd]
hwdec=vaapi

[no-av1]
ytdl-format=bestvideo[vcodec!*=av01][height<=?1080]+bestaudio/best[height<=?1080]/bestvideo[vcodec!*=av01]+bestaudio/best
