# -----------------------
# NOCTALIA SHELL
# -----------------------

# Open session menu
bind=SUPER,Escape,spawn,noctalia msg panel-toggle session

# Lock session
bind=SUPER+SHIFT,Escape,spawn,noctalia msg session lock

# Open launcher
bind=SUPER,space,spawn,noctalia msg panel-toggle launcher

# Open control center
bind=SUPER,s,spawn,noctalia msg panel-toggle control-center

# Open settings
bind=SUPER,comma,spawn,noctalia msg settings-toggle

# Open clipboard
bind=SUPER+SHIFT,v,spawn,noctalia msg panel-toggle clipboard

# Take Screenshot: Focused Monitor
# bind=none,Print,spawn,noctalia msg screenshot-fullscreen

# Take Screenshot: Region
# bind=SHIFT,Print,spawn,noctalia msg screenshot-region

# Take Screenshot: Picker
# bind=ALT,Print,spawn,noctalia msg screenshot-fullscreen pick
