# -----------------------
# LAYERS
# -----------------------
# Notifications layer
layerrule=layer_name:noctalia-notification,shield_when_capture:1

# -----------------------
# Windows
# -----------------------
# Noctalia Settings
windowrule=appid:dev.noctalia.Noctalia,title:Noctalia Settings,isfloating:1,centerwin,width:0.5,height:0.8

