[metadata]
name = "explorer-gitrepos"
requirements = ["fd", "eza"]
description = """
A channel to select from git repositories on your local machine as a project.

This channel uses
1. `fd` to find directories that contain a `.git` subdirectory.
2. `eza` to preview directory structure.
"""

[source]
command = "fd -g .git -HL -t d -d 10 --prune ~ -E .cache -E .cargo -E .repos -E .local --exec dirname '{}'"
display = "{split:/:-1}"

[preview]
command = "eza -a -T -L 3 --git-ignore --color always --icons always '{}'"
shell = "nu"

[ui.remote_control]
disabled = true

[ui.preview_panel]
size = 55

[keybindings]
tab = "select_next_entry"
backtab = "select_prev_entry"
ctrl-j = "select_next_entry"
ctrl-k = "select_prev_entry"
q = "quit"
enter = "actions:zellij"
shift-g = "actions:git"
shift-e = "actions:explore"
shift-c = "actions:cd"

[actions.zellij]
description = "Open a terminal with an new zellij session or attaches to existing one."
command = "~/.config/television/shell-scripts/open-zellij.nu {}"
shell = "nu"
mode = "fork"

[actions.explore]
description = "Open repository in a new terminal window with file manager runnign. Shell must have FILE_MANAGER variable"
command = "~/.config/television/shell-scripts/open-directory.nu {} --use-file-manager"
shell = "nu"
mode = "fork"

[actions.cd]
description = "Open a new terminal with cwd in selected repository directory"
command = "~/.config/television/shell-scripts/open-directory.nu {}"
shell = "nu"
mode = "fork"

[actions.git]
description = "Open repository in new terminal window with running git client."
command = "~/.config/television/shell-scripts/open-git.nu {}"
shell = "nu"
mode = "fork"
